BBPATH .= ":${LAYERDIR}"
BBFILES += "\
  ${LAYERDIR}/recipes-*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
"
LICENSE_PATH += "${LAYERDIR}/licenses"

BBFILE_COLLECTIONS += "catplay"
BBFILE_PATTERN_catplay = "^${LAYERDIR}/"
BBFILE_PRIORITY_catplay = "7"

LAYERSERIES_COMPAT_catplay = "scarthgap"

require conf/catplay/distro-config.conf