BBPATH .= ":${LAYERDIR}"
BBFILES += "\
  ${LAYERDIR}/recipes-*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "sunxi"
BBFILE_PATTERN_sunxi = "^${LAYERDIR}/"
BBFILE_PRIORITY_sunxi = "7"

LAYERSERIES_COMPAT_sunxi = "scarthgap wrynose"
