# More busybox!
#VIRTUAL-RUNTIME_useradd = "busybox"
#VIRTUAL-RUNTIME_modutils = "busybox"
#VIRTUAL-RUNTIME_shadow-utils = "busybox"
VIRTUAL-RUNTIME_login_manager = "busybox"
#VIRTUAL-RUNTIME_kmod = "busybox"
#VIRTUAL-RUNTIME_init_manager = "sysvinit"
VIRTUAL-RUNTIME_init_manager = "busybox"

