DISTRO_VERSION = "c2a"

DISTRO_FEATURES = "ipv4 ipv6 usbhost usbgadget wifi bluetooth vfat lto ld-is-lld"
DISTRO_FEATURES_BACKFILL_CONSIDERED = "pulseaudio gobject-introspection-data ldconfig"

C2A_SYSTEM_PACKAGES = "\
    initscripts \
    busybox \
    bluez5 \
    dbus \
    wireless-regdb-static \
    hostapd \
    wpa-supplicant \
    c2a-overlay-init \
    dropbear openssh-sftp-server \
"
PACKAGE_CLASSES = "package_ipk"

# Fix respawn spam
SYSVINIT_ENABLED_GETTYS = ""

USE_NLS = "no"

# OpenEmbedded uses pigz by default which results in bad compression ratio for kernel
PREFERRED_PROVIDER_gzip-native = "gzip-native"
PROVIDES:remove:pn-pigz-native:class-native = "gzip-native"
CONVERSION_DEPENDS_gz:forcevariable = "gzip-native"