require conf/distro/include/lto.inc
require conf/distro/include/c2a/gcsections.conf

require conf/distro/include/c2a/common.conf
require conf/distro/include/c2a/busybox.conf
require conf/distro/include/c2a/clang.conf
require conf/distro/include/c2a/lto.conf
require conf/distro/include/c2a/rust.conf

require conf/distro/include/c2a/image/cleanup.conf
require conf/distro/include/c2a/image/dtc.conf
require conf/distro/include/c2a/image/firmware-conflicts.conf
require conf/distro/include/c2a/image/jffs2.conf
require conf/distro/include/c2a/image/upx.conf
require conf/distro/include/c2a/image/wic.conf

