### BLACKLIST: no .o-based thin-lto

BUILD_OPTIMIZATION:pn-zlib:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-zlib:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-ncurses:forcevariable = "-Os"
SELECTED_OPTIMIZATION:pn-ncurses:forcevariable = "-Os"

BUILD_OPTIMIZATION:pn-ttyrun:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-ttyrun:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-libxcrypt:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-libxcrypt:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-libtircp:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-libtirpc:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-sysvinit:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-sysvinit:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-busybox:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-busybox:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-perl:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-perl:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-bash:forcevariable = "-Os"
SELECTED_OPTIMIZATION:pn-bash:forcevariable = "-Os"

BUILD_OPTIMIZATION:pn-python3:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-python3:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-alsa-lib:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-alsa-lib:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-libcap:forcevariable = "-Os"
SELECTED_OPTIMIZATION:pn-lipcap:forcevariable = "-Os"

BUILD_OPTIMIZATION:pn-iptables:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-iptables:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-readline:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-readline:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-glib-2.0:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-glib-2.0:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-wpa-supplicant:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-wpa-supplicant:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-iw:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-iw:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-dropbear:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-dropbear:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-shared-mime-info:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-shared-mime-info:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-bluez5:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-bluez5:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-iproute2:forcevariable = "-Oz"
SELECTED_OPTIMIZATION:pn-iproute2:forcevariable = "-Oz"

BUILD_OPTIMIZATION:pn-make-mod-scripts:forcevariable = "-Os"
SELECTED_OPTIMIZATION:pn-make-mod-scripts:forcevariable = "-Os"
