## BLACKLIST: Segmation fault
LTO:pn-zlib:toolchain-clang = ""

TOOLCHAIN:pn-elfutils:forcevariable = "gcc"
TOOLCHAIN:pn-make-mod-scripts:forcevariable = "gcc"

# MIPS fixes

TOOLCHAIN:pn-libffi:mipsarch:forcevariable = "gcc"
TOOLCHAIN:pn-libxcrypt:mipsarch:forcevariable = "gcc"

LDFLAGS:append:pn-libxcrypt:toolchain-gcc = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', ' -Wl,--undefined-version', '', d)}"

LDFLAGS:append:pn-libxcrypt:toolchain-gcc = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', ' -fuse-ld=bfd', '', d)}"
LDFLAGS:remove:pn-libxcrypt:toolchain-gcc = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', '-fuse-ld=lld', '', d)}"

LDFLAGS:append:pn-libffi:toolchain-gcc = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', ' -fuse-ld=bfd', '', d)}"
LDFLAGS:remove:pn-libffi:toolchain-gcc = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', '-fuse-ld=lld', '', d)}"

LDFLAGS:append:pn-busybox:mipsarch = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', ' -fuse-ld=bfd', '', d)}"
LDFLAGS:remove:pn-busybox:mipsarch = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', '-fuse-ld=lld', '', d)}"

LDFLAGS:append:pn-perl:mipsarch = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', ' -fuse-ld=bfd', '', d)}"
LDFLAGS:remove:pn-perl:mipsarch = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', '-fuse-ld=lld', '', d)}"
