TCLIBC = "musl"

ENABLE_WIDEC = "false"
ENABLE_WIDEC:class-native = "true"

#| checking whether -lc should be explicitly linked in... no
#| checking dynamic linker characteristics... configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.
#| WARNING: exit code 1 from a shell command.
# NOTE: recipe gcc-runtime-13.4.0-r0: task do_configure: Failed
# /workdir/build/tmp-musl/work/cortexa7t2hf-neon-oe-linux-musleabi/gcc-runtime/13.4.0/recipe-sysroot/usr/lib/crt1.o: file not recognized: file format not recognized
#LTO:remove:pn-musl = "-ffat-lto-objects"
LTO:forcevariable:pn-musl = ""

# | fatal error: error in backend: unsupported directive in streamer
# | PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
LTO:forcevariable:pn-musl:mipsarch = ""

# mips-oe-linux-ld.lld: error: relocation R_MIPS_32 cannot be used against local symbol; recompile with -fPIC (libgcc.a)
LDFLAGS:append:pn-musl:mipsarch:toolchain-clang = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', ' -fuse-ld=bfd', '', d)}"
LDFLAGS:remove:pn-musl:mipsarch:toolchain-clang = "${@bb.utils.contains('DISTRO_FEATURES', 'ld-is-lld', '-fuse-ld=lld', '', d)}"
