#RUST_VERSION = "1.86.0"
#require conf/distro/include/rust_versions.inc

RUST_PANIC_STRATEGY:class-target = "abort"
CARGO_FEATURES:class-target = ""
#CARGO_FEATURES:class-native = "panic-unwind backtrace"
DEPENDS:remove:libc-musl:pn-libstd-rs = "libunwind"

