blacklist brcmfmac
blacklist brcmutil
blacklist bluetooth
blacklist btbcm
blacklist hci_uart
blacklist vc4
blacklist snd_bcm2835
blacklist i2c_bcm2835
blacklist spi_bcm2835
blacklist i2c_dev
blacklist v3d
blacklist drm
blacklist drm_kms_helper
blacklist rpi_hevc_dec
blacklist bcm2708_fb
