# Flash layout
# Needs to be in sync with: .dts AND brandy-2.0 patches
C2A_FLASH_SIZE = "16M" 

FLASH_BOOT0_BIN = "${DEPLOY_DIR_IMAGE}/sunxi-brandy/simpleboot-v821b-falcon2.bin"
FLASH_KERNEL_BIN = "${DEPLOY_DIR_IMAGE}/c2rvImage"
FLASH_INITRD_BIN = "${DEPLOY_DIR_IMAGE}/${C2A_INITRAMFS_IMAGE}-${MACHINE}.erofs-lz4hc"
FLASH_PERSIST_BIN = "${IMGDEPLOYDIR}/${IMAGE_LINK_NAME}.${C2A_ROOTFS_FSTYPE}"

# boot0 256KB
# kernel 4MB
# initrd ~11MB
# persist ~0.75MB

C2A_FLASH_PARTITIONS = "\
    ${FLASH_BOOT0_BIN} 0x00000000 0x00040000 \
    ${FLASH_KERNEL_BIN} 0x00040000 0x00400000 \
    ${FLASH_INITRD_BIN} 0x00440000 0x00b00000 \
    ${FLASH_PERSIST_BIN} 0x00f40000 0x000C0000 \
"
