PREFERRED_PROVIDER_virtual/kernel = "linux-sunxi"
PREFERRED_PROVIDER_virtual/dtb = "woo-dtb"
PREFERRED_PROVIDER_virtual/opensbi = "sunxi-opensbi-open"

# Keep flash bundle placement in sync with Falcon FEL and recov.py.
# Also, this change recovers first 4MB of RAM but requires a patched bootloader
# so the default kernel loadaddr stays 0x80400000 for backwards compatibility
C2A_RISCV_BUNDLE_DTB_LOADADDRESS = "0x80f00000"
C2A_RISCV_BUNDLE_KERNEL_LOADADDRESS = "0x80000000"
C2A_RISCV_BUNDLE_OPENSBI_LOADADDRESS = "0x80fc0000"

SRC_URI:append:pn-linux-sunxi = " file://defconfig"

KERNEL_DEVICETREE_BUNDLE = "0"
KERNEL_DEVICETREE = ""

#KERNEL_CLASSES = "kernel-uimage"
#KEEPUIMAGE = "yes"

#KERNEL_IMAGETYPE = "Image"
#KERNEL_IMAGETYPES = "Image Image.gz vmlinux"
