C2A_KERNEL_EXTRA_CONFIG[CONFIG_CMDLINE] = ""
C2A_KERNEL_EXTRA_CONFIG[CONFIG_CMDLINE_OVERRIDE] = "n"
C2A_KERNEL_EXTRA_CONFIG[CONFIG_BLK_DEV_RAM] = "y"
C2A_KERNEL_EXTRA_CONFIG[CONFIG_BLK_DEV_INITRD] = "y"
C2A_KERNEL_EXTRA_CONFIG[CONFIG_BLK_DEV_RAM_COUNT] = "16"
C2A_KERNEL_EXTRA_CONFIG[CONFIG_BLK_DEV_RAM_SIZE] = "16384"

C2A_KERNEL_EXTRA_CONFIG[CONFIG_EARLY_PRINTK] = "y"
C2A_KERNEL_EXTRA_CONFIG[CONFIG_EARLY_PRINTK_8250] = "y"
C2A_KERNEL_EXTRA_CONFIG[CONFIG_EARLY_CONSOLE] = "y"
C2A_KERNEL_EXTRA_CONFIG[CONFIG_USE_GENERIC_EARLY_PRINTK_8250] = "y"

