
DEFAULTTUNE = "riscv32"
MACHINEOVERRIDES =. "woo:v821:"

MACHINE_FEATURES += "wifi bluetooth"

LDFLAGS:append:pn-dropbear:mipsarch = " -static"
PREFERRED_PROVIDER_virtual/bootloader = "sunxi-brandy"

# Or aic8800-fw-aic8800d80 aic8800
MACHINE_FIRMWARE:append = " carlinkit-otalib carlinkit-init carlinkit-mini-nvram c2a-firmware-rtl8733bs"
CATPLAY_DEBUG_BUILD ?= "0"

DISTRO = "c2a-musl"
JFFS2_ERASEBLOCK = "0x1000"

C2A_SYSTEM_PACKAGES:remove = "wpa-supplicant"

require conf/machine/include/riscv/tune-riscv.inc

include conf/machine/include/v821/kernel.conf
include conf/machine/include/v821/wic.conf

# UPX not compatible with riscv32
IMAGE_UPX_TARGETS:forcevariable = ""