require conf/machine/include/clk-mini-ultra/shared.conf
require conf/machine/include/clk-mini-ultra/flash-nor.conf

require conf/system/include/c2a/machine-boot/erofs-base.conf
#require conf/system/include/c2a/machine-boot/initramfs.conf

# catplay-bench
MACHINE_FIRMWARE:append = " catplay-g-iphone catplay "