IMAGE_CLEANUP_TARGETS += "\
    /usr/bin/isotest \
    /usr/bin/rctest \
    /usr/bin/mpris-proxy \
    /usr/bin/l2test \
    /usr/bin/rfcomm \
    /usr/bin/l2ping \
    /usr/bin/btmon \
    /usr/bin/bluemoon \
    /usr/bin/btattach \
    /usr/bin/dbus-monitor \
    /usr/bin/dbus-send \
    /usr/bin/dbus-launch \
    /usr/bin/dbus-run-session \
    /usr/bin/dbus-update-activation-environment \
    /usr/bin/hex2hcd \
    /lib/firmware/LICENSE.* \
"

IMAGE_CLEANUP_TARGETS += "\
    /sbin/sulogin /sbin/sulogin.util-linux \
    /usr/bin/newgrp /usr/bin/newgrp.shadow \
    /usr/bin/groups /usr/bin/groups.shadow \
    /bin/su /bin/su.shadow /bin/login.shadow \
"
