C2A_BOOTARGS ?= "${C2A_APPEND}"
C2A_APPEND ??= ""

C2A_DTC_STRINGS += "C2A_APPEND C2A_BOOTARGS"
C2A_DTC_INTS += "C2A_UBOOT_OFFSET_HEX C2A_UBOOT_SIZE_HEX"
C2A_DTC_INTS += "C2A_UBOOT_SPL_OFFSET_HEX C2A_UBOOT_SPL_SIZE_HEX"
C2A_DTC_INTS += "C2A_KERNEL_OFFSET_HEX C2A_KERNEL_SIZE_HEX"
C2A_DTC_INTS += "C2A_ROOTFS_OFFSET_HEX C2A_ROOTFS_SIZE_HEX"
C2A_DTC_INTS += "C2A_FLASH_SIZE_HEX"

C2A_OFFSET_HELPER_VARS += "C2A_FLASH_SIZE C2A_UBOOT_OFFSET C2A_UBOOT_SIZE C2A_UBOOT_SPL_OFFSET C2A_UBOOT_SPL_SIZE C2A_KERNEL_OFFSET C2A_KERNEL_SIZE C2A_ROOTFS_OFFSET C2A_ROOTFS_SIZE"
