IMAGE_UPX_TARGETS += "/usr/sbin/dropbearmulti"
IMAGE_UPX_TARGETS += "/usr/libexec/sftp-server"
#IMAGE_UPX_TARGETS += "/usr/libexec/bluetooth/bluetoothd"
#IMAGE_UPX_TARGETS += "/usr/sbin/hostapd"
#IMAGE_UPX_TARGETS += "/usr/sbin/wpa_supplicant"
IMAGE_UPX_TARGETS += "/usr/bin/bluetoothctl"
