C2A_WICVARS += "UBOOT_BINARY KERNEL_FIT_LINK_NAME KERNEL_ARTIFACT_LINK_NAME"
C2A_WICVARS += "C2A_FLASH_SIZE C2A_UBOOT_SPL_OFFSET C2A_UBOOT_SPL_SIZE C2A_UBOOT_OFFSET C2A_UBOOT_SIZE"
C2A_WICVARS += "C2A_KERNEL_OFFSET C2A_KERNEL_SIZE C2A_ROOTFS_OFFSET C2A_ROOTFS_SIZE"
C2A_WICVARS += "C2A_WIC_UBOOT_PATH C2A_WIC_KERNEL_PATH C2A_WIC_ROOTFS_PATH"
