BBPATH .= ":${LAYERDIR}"
BBFILES += "\
  ${LAYERDIR}/recipes-*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
"
LICENSE_PATH += "${LAYERDIR}/licenses"

BBFILE_COLLECTIONS += "carplay"
BBFILE_PATTERN_carplay = "^${LAYERDIR}/"
BBFILE_PRIORITY_carplay = "6"

LAYERSERIES_COMPAT_carplay = "scarthgap"