C2A_INITRAMFS_FSTYPES = "erofs-lz4hc"
C2A_EXTRA_FSTYPES = "tar.gz"

C2A_INITRAMFS_IMAGE = "c2a-initrd-image"

INITRAMFS_IMAGE_BUNDLE = "0"
INITRAMFS_IMAGE := "${C2A_INITRAMFS_IMAGE}"
INITRAMFS_FSTYPES := "${C2A_INITRAMFS_FSTYPES}"