require conf/system/include/c2a/machine-boot/erofs-base.conf

C2A_APPEND = "root=/dev/initrd rootfstype=erofs rw quiet"

KERNEL_CLASSES  = "kernel-fitimage-c2a"
KERNEL_IMAGETYPES = "zImage fitImage"
KERNEL_IMAGETYPE = "fitImage"