C2A_INITRAMFS_FSTYPES = "cpio.zst"
C2A_EXTRA_FSTYPES = "tar.gz"

C2A_INITRAMFS_IMAGE = "c2a-initrd-image"

INITRAMFS_IMAGE_BUNDLE = "1"
INITRAMFS_IMAGE := "${C2A_INITRAMFS_IMAGE}"
INITRAMFS_FSTYPES := "${C2A_INITRAMFS_FSTYPES}"