BBPATH .= ":${LAYERDIR}"
BBFILES += "\
  ${LAYERDIR}/recipes-*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "carlinkit-mini"
BBFILE_PATTERN_carlinkit-mini = "^${LAYERDIR}/"
BBFILE_PRIORITY_carlinkit-mini = "7"

LAYERSERIES_COMPAT_carlinkit-mini = "scarthgap"