BBPATH .= ":${LAYERDIR}"
BBFILES += "\
  ${LAYERDIR}/recipes-*/*.bb \
  ${LAYERDIR}/recipes-*/*/*.bb \
  ${LAYERDIR}/recipes-*/*.bbappend \
  ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "carlinkit"
BBFILE_PATTERN_carlinkit = "^${LAYERDIR}/"
BBFILE_PRIORITY_carlinkit = "7"

LAYERSERIES_COMPAT_carlinkit = "scarthgap"