# Flash layout
# Needs to be in sync with: .dts, .wks AND u-boot config.h/defconfig
C2A_FLASH_SIZE ?= "16M" 

# --> Signed legacy u-boot.imx (SPL)
CARLINKIT_UBOOT_OFFSET ?= "1K"
CARLINKIT_UBOOT_SIZE   ?= "127K"

# --> CSF with ENV provisioning block appended at the end
CARLINKIT_UBOOT_CSF_OFFSET ?= "128K"
CARLINKIT_UBOOT_CSF_SIZE   ?= "64K"

# --> reserved, left zeroed in our image
CARLINKIT_UBOOT_ENV_OFFSET ?= "192K"
CARLINKIT_UBOOT_ENV_SIZE   ?= "64K"

# --> Modern uboot.bin. 
C2A_UBOOT_OFFSET ?= "256K"
C2A_UBOOT_SIZE   ?= "512K"

# --> Kernel (fitImage)
C2A_KERNEL_OFFSET ?= "768K"
C2A_KERNEL_SIZE   ?= "14000K"

# --> Persistance overlay ("rootfs")
C2A_ROOTFS_OFFSET ?= "16128K"
C2A_ROOTFS_SIZE   ?= "256K"

C2A_OFFSET_HELPER_VARS:append = " CARLINKIT_UBOOT_OFFSET CARLINKIT_UBOOT_SIZE CARLINKIT_UBOOT_CSF_OFFSET CARLINKIT_UBOOT_CSF_SIZE CARLINKIT_UBOOT_ENV_OFFSET CARLINKIT_UBOOT_ENV_SIZE"

# --> Fail u-boot build if too large to fit
### C2A_UBOOT_SIZE_ENFORCE ?= "1"
