MACHINEOVERRIDES =. "imx6ul-c2a:mx6ul:"
DISTRO = "c2a-musl"
CATPLAY_DEBUG_BUILD ?= "0"
JFFS2_ERASEBLOCK = "0x10000"

include conf/machine/include/imx-base.inc
include conf/machine/include/arm/armv7a/tune-cortexa7.inc

MACHINE_FEATURES += "wifi bluetooth"
MACHINE_FIRMWARE:remove = "linux-firmware-imx-sdma-imx7d firmware-imx-vpu-imx6q firmware-imx-vpu-imx6d"
MACHINE_FIRMWARE:append = " carlinkit-nvram carlinkit-rgb carlinkit-init carlinkit-otalib catplay"
#MACHINE_FIRMWARE:append = " tcpdump"

# That's a legacy driver that also doesn't compile with mainline
# MACHINE_EXTRA_RRECOMMENDS:remove = "kernel-module-nxp-wlan"
include conf/machine/include/imx6ul-c2a/flash.conf
include conf/machine/include/imx6ul-c2a/kernel.conf
include conf/machine/include/imx6ul-c2a/uboot.conf
include conf/machine/include/imx6ul-c2a/wic.conf