# C2A_KERNEL_EXTRA_CONFIG[CONFIG_BT_HCIUART_BCM] = "n"
# C2A_KERNEL_EXTRA_CONFIG[CONFIG_BT_HCIUART_H4] = "n"
# C2A_KERNEL_EXTRA_CONFIG[CONFIG_BT_HCIUART_LL] = "n"
# C2A_KERNEL_EXTRA_CONFIG[CONFIG_BT_HCIUART_MRVL] = "n"
# C2A_KERNEL_EXTRA_CONFIG[CONFIG_BT_HCIUART_3WIRE] = "n"
# C2A_KERNEL_EXTRA_CONFIG[CONFIG_BT_BCM] = "n"
