# U-Boot IMX build config
SPL_BINARY:pn-u-boot-imx = ""
UBOOT_MAKE_TARGET:pn-u-boot-imx = "u-boot.imx"
#UBOOT_SUFFIX:pn-u-boot-imx = "imx"
UBOOT_SUFFIX:pn-u-boot-imx = "bin"

# U-Boot
PREFERRED_PROVIDER_u-boot = "u-boot-imx"
IMX_DEFAULT_BOOTLOADER = "u-boot-imx"
UBOOT_CONFIG = "imx6ul-c2a"
UBOOT_CONFIG[imx6ul-c2a] = "imx6ul-c2a_defconfig"
