PREFERRED_PROVIDER_virtual/kernel = "linux-letux"
PREFERRED_PROVIDER_virtual/dtb = "carlinkit-mini-dtb"
KERNEL_DEVICETREE_BUNDLE = "0"
KERNEL_DEVICETREE = "ingenic/carlinkit-mini-ultra-nor.dtb"

KERNEL_CLASSES = "kernel-uimage"
KEEPUIMAGE = "yes"

KERNEL_IMAGETYPE = "uzImage.bin"
KERNEL_IMAGETYPES = "vmlinuz.bin uzImage.bin uImage"

# binwalk ota.bin 
# DECIMAL       HEXADECIMAL     DESCRIPTION
# --------------------------------------------------------------------------------
# 131072        0x20000         uImage header, header size: 64 bytes, header CRC: 0xE21AD8A5, created: 2025-07-31 06:41:59, image size: 3088384 bytes, Data Address: 0x80F00000, Entry Point: 0x80F00000, data CRC: 0x7341E837, OS: Linux, CPU: MIPS, image type: OS Kernel Image, compression type: none, image name: "Linux-4.4.94"
# 148064        0x24260         gzip compressed data, maximum compression, has original file name: "vmlinux.bin", from Unix, last modified: 2025-07-31 06:41:58
# 3219520       0x312040        Squashfs filesystem, little endian, version 4.0, compression:gzip (non-standard type definition), size: 12039510 bytes, 708 inodes, blocksize: 131072 bytes, created: 2025-07-31 06:42:29
