
DEFAULTTUNE = "mips32r2el"
MACHINEOVERRIDES =. "clk-mini-ultra:ingenic-x1600:"
PACKAGE_EXTRA_ARCHS:append = " ingenic-x1600"

MACHINE_FEATURES += "wifi bluetooth"

LDFLAGS:append:pn-dropbear:mipsarch = " -static"
PREFERRED_PROVIDER_virtual/bootloader = "u-boot-letux"

MACHINE_FIRMWARE:append = " carlinkit-otalib aic8800 carlinkit-init carlinkit-mini-nvram aic8800-fw-aic8800d80"
CATPLAY_DEBUG_BUILD ?= "0"

DISTRO = "c2a-musl"
JFFS2_ERASEBLOCK = "0x1000"

#C2A_SYSTEM_PACKAGES:remove = "wpa-supplicant"

include conf/machine/include/mips/tune-mips32r2.inc
include conf/machine/include/clk-mini-ultra/kernel.conf
include conf/machine/include/clk-mini-ultra/wic.conf
